#!/usr/bin/env python

from typing import Any, Mapping, Optional, Sequence


def agent_nsx_arguments(
    params: Mapping[str, Any], hostname: str, ipaddress: Optional[str]
) -> Sequence[str]:
    args = []
    args += ["--address", hostname]
    args += ["--username", params["user"]]
    args += ["--password", passwordstore_get_cmdline("%s", params["password"])]

    if params.get("cert", True):
        args += ["--no-cert-check"]

    return args


special_agent_info["nsx"] = agent_nsx_arguments
