#!/usr/bin/env python
# -*- encoding: utf-8 -*-

def agent_nsx_arguments(params, hostname, ipaddress):
    args = []
    args += ["--address", hostname]
    args += ["--username", params["user"]]
    args += ["--password", passwordstore_get_cmdline("%s", params["password"])]

    if params.get("cert", True):
        args += ["--no-cert-check"]
    return args

special_agent_info['nsx'] = agent_nsx_arguments
