#!/usr/bin/env python3
# -*- encoding: utf-8; py-indent-offset: 4 -*-

# NOTE: Careful when replacing the *-import below with a more specific import. This can cause
# problems because it might remove variables from the check-context which are necessary for
# resolving legacy discovery results such as [("SUMMARY", "diskstat_default_levels")]. Furthermore,
# it might also remove variables needed for accessing discovery rulesets.
from cmk.base.check_legacy_includes.cpu_load import *  # pylint: disable=wildcard-import,unused-wildcard-import

def parse_nsx_cpu(info):
    try:
        return {
            "num_cpus": int(info[0][0]),
            "load": list(map(float, info[1][0:3]))
        }
    except (IndexError, ValueError):
        return {}

def inventory_nsx_cpu(parsed):
    return [(None, None)]

def check_nsx_cpu(item, params, parsed):
    return check_cpu_load_generic(params, parsed['load'], parsed['num_cpus'])


check_info['nsx_cpu'] = {
    'parse_function': parse_nsx_cpu,
    'inventory_function': inventory_nsx_cpu,
    'check_function': check_nsx_cpu,
    'service_description': 'CPU utilization',
    #'group': 'cpu_utilization_os',

    'group': 'cpu_utilization',
    'has_perfdata': True,
}
