#!/usr/bin/env python3
# -*- encoding: utf-8; py-indent-offset: 4 -*-

# NOTE: Careful when replacing the *-import below with a more specific import. This can cause
# problems because it might remove variables from the check-context which are necessary for
# resolving legacy discovery results such as [("SUMMARY", "diskstat_default_levels")]. Furthermore,
# it might also remove variables needed for accessing discovery rulesets.
from cmk.base.check_legacy_includes.mem import *  # pylint: disable=wildcard-import,unused-wildcard-import

def parse_nsx_mem(info):
    if not info:
        return {}

    values = {}
    for line in info:
        values[line[0]] = int(line[1]) * 1024
    return values

def inventory_nsx_mem(parsed):
    return [(None, {})]

def check_nsx_mem(_no_item, params, parsed):
    results = check_memory_dict(parsed, params)
    for state, infotext, perfdata in results.values():
        yield state, infotext, perfdata


check_info['nsx_memory'] = {
    "parse_function": parse_nsx_mem,
    "check_function": check_nsx_mem,
    "inventory_function": inventory_nsx_mem,
    "service_description": "Memory used",
    "group": "nsx_memory",
    "has_perfdata": True,
    "default_levels_variable": "memory_default_levels",
}
