#!/usr/bin/env python3
# -*- encoding: utf-8; py-indent-offset: 4 -*-

def parse_edges_status(info):
    edges = {}
    for line in info:
        instance = edges.setdefault(
            line[0], {
                "id": line[1],
                "status": line[2],
            })
    return edges


def inventory_edges_status(parsed):
    for name, edge in parsed.items():
        yield name, {}


@get_parsed_item_data
def check_edges_status(_item, params, data):
    if params is None:
        params = {}

    returncode = 3
    edgestatus = data['status']
    if edgestatus == "UP":
        returncode = 0
    elif edgestatus == "YELLOW":
        returncode = 1
    elif edgestatus == "DOWN":
        returncode = 2
    yield returncode, "State: %s" % (edgestatus)
    yield 0, "ID %s" % (data['id'])


check_info['nsx_edges'] = {
    'parse_function': parse_edges_status,
    'inventory_function': inventory_edges_status,
    'check_function': check_edges_status,
    'service_description': 'NSX Edge %s', 
    'has_perfdata': False,
}
