name: build

on:
  push:
    branches:
    - '*'
    tags-ignore:
    - 'v*'
  pull_request:

jobs:
  build:
    name: Build Checkmk package
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - uses: apoxa/build-checkmk-extension@28b5bc9e1eb5a41de1f3751b0e454527e46c2570
      id: cmkpkg
      with:
        cmk-version: 2.0.0b4

    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: ${{ steps.cmkpkg.outputs.pkgfile }}
        path: ${{ steps.cmkpkg.outputs.pkgfile }}
